language: node_js
node_js:
- '8.4'
before_script:
  - echo -e "Host saferglobe.seravo.fi\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
script: yarn build
before_deploy:
- openssl aes-256-cbc -K $encrypted_a5a4b6243b23_key -iv $encrypted_a5a4b6243b23_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
    -
  on:
    branch: master
